### ISSUE TITLE
Can't load 1.11 mappings (FileNotFound Start.java)

### ISSUE THREAD

**Issue by MiniDigger** [bspkrs/MCPMappingViewer#14]
just tried to spin up MMV to look at some 1.11 stuff and saw that it can't load the mappings on my system. Loading 1.10 stable works just fine.
![http://i.minidigger.me/2016/12/javaw_06_20-01-42.png](http://i.minidigger.me/2016/12/javaw_06_20-01-42.png)

```An error has occurred - give bspkrs this stack trace (which has been copied to the clipboard)

java.io.FileNotFoundException: C:\Users\Martin\.cache\MCPMappingViewer\1.11\patches\Start.java (Das System kann den angegebenen Pfad nicht finden)
    at java.io.FileOutputStream.open0(Native Method)
    at java.io.FileOutputStream.open(Unknown Source)
    at java.io.FileOutputStream.<init>(Unknown Source)
    at java.io.FileOutputStream.<init>(Unknown Source)
    at bspkrs.mmv.RemoteZipHandler.extractZip(RemoteZipHandler.java:233)
    at bspkrs.mmv.RemoteZipHandler.checkRemoteZip(RemoteZipHandler.java:119)
    at bspkrs.mmv.McpMappingLoader.getSubDirForZip(McpMappingLoader.java:122)
    at bspkrs.mmv.McpMappingLoader.<init>(McpMappingLoader.java:85)
    at bspkrs.mmv.gui.MappingGui$RefreshActionListener$1.run(MappingGui.java:1148)```

I am on win 10  1607 64bit and java 8 u91 64bit. 
reproduced it on a clean win10 vm

**Comment by bspkrs** [comment]
Thanks, I am looking into this. Seems like it might be a problem with the
way the srg zip files were created, so I'll let you know when it's resolved.

**Comment by bspkrs** [comment]
Doing builds for 1.0.1 to fix this. Thanks for reporting it.

**Comment by bspkrs** [comment]
I'm not sure why the page isn't refreshing for me, but you can download it from here:
http://bspk.rs/MC/MCPMappingViewer/MCPMappingViewer_1.0.1.jar

**Comment by MiniDigger** [comment]
thanks for looking at it, will give it a try later today.

**Comment by MiniDigger** [comment]
that fixed it, thank you

**Comment by LeafHacker** [comment]
@bspkrs can you add 1.0.1 to the github releases tab?

This should happen automatically if you tag the relevant commit as `1.0.1`:

```bash
git tag 1.0.1 95dd1c5
git push origin 1.0.1 # or "git push --tags" for all tags, normally "git push" ignores tags
```

Also, FYI mcp940-pre1 still has mapping viewer 1.0.0, probably because it isn't tagged as a release.
