### ISSUE TITLE
Unable to View 1.13+ mappings | Missing SRG mapping zip

### ISSUE THREAD

**Issue by willies952002** [bspkrs/MCPMappingViewer#18]
## Stacktrace
```
java.io.FileNotFoundException: http://export.mcpbot.bspk.rs/mcp/1.13.1/mcp-1.13.1-srg.zip
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1890)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
    at bspkrs.mmv.RemoteZipHandler.checkRemoteZip(RemoteZipHandler.java:99)
    at bspkrs.mmv.McpMappingLoader.getSubDirForZip(McpMappingLoader.java:122)
    at bspkrs.mmv.McpMappingLoader.<init>(McpMappingLoader.java:85)
    at bspkrs.mmv.gui.MappingGui$RefreshActionListener$1.run(MappingGui.java:1153)
```

Idea: if the mappings aren't available for a specific version, state that the mappings are not yet available (which is most likely the case)

**Comment by MiniDigger** [comment]
Even now that the versions are available it still fails :/

**Comment by CammiePone** [comment]
Yep. It is sad.

**Comment by hohserg1** [comment]
I'm have this error too

**Comment by MattSturgeon** [comment]
AFAICT srg mappings are no longer published to http://export.mcpbot.bspk.rs/mcp, instead they end up [on the forge maven](https://files.minecraftforge.net/maven/de/oceanlabs/mcp/) as the [mcp_config](https://github.com/MinecraftForge/MCPConfig) project, e.g. https://files.minecraftforge.net/maven/de/oceanlabs/mcp/mcp_config/index_1.13.2.html

If the version is above 1.13, then MCPMappingViewer should look there instead.

**Comment by dmodoomsirius** [comment]
`An error has occurred - give bspkrs this stack trace (which has been copied to the clipboard)

java.io.FileNotFoundException: http://export.mcpbot.bspk.rs/mcp/1.14.3/mcp-1.14.3-srg.zip
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
    at bspkrs.mmv.RemoteZipHandler.checkRemoteZip(RemoteZipHandler.java:99)
    at bspkrs.mmv.McpMappingLoader.getSubDirForZip(McpMappingLoader.java:122)
    at bspkrs.mmv.McpMappingLoader.<init>(McpMappingLoader.java:85)
    at bspkrs.mmv.gui.MappingGui$RefreshActionListener$1.run(MappingGui.java:1153)`
getting this as well with the latest.

**Comment by RunoLight** [comment]
bump
