### ISSUE TITLE
MCP mapping viewer latest 1.0.3 no work

### ISSUE THREAD

**Issue by jabask3dd3r** [bspkrs/MCPMappingViewer#33]
i try to load 1.12.2 mappings 
it get error->    
An error has occurred - give bspkrs this stack trace (which has been copied to the clipboard)

javax.net.ssl.SSLException: Received fatal alert: internal_error
    at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:129)
    at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
    at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:308)
    at java.base/sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:279)
    at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:181)
    at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:164)
    at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1152)
    at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1063)
    at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:402)
    at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567)
    at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
    at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1581)
    at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509)
    at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:245)
    at bspkrs.mmv.RemoteZipHandler.checkRemoteZip(RemoteZipHandler.java:99)
    at bspkrs.mmv.McpMappingLoader.getSubDirForZip(McpMappingLoader.java:132)
    at bspkrs.mmv.McpMappingLoader.<init>(McpMappingLoader.java:95)
    at bspkrs.mmv.gui.MappingGui$RefreshActionListener$1.run(MappingGui.java:1153)

https://youtu.be/N-IoSHu5dWY check this video for see error

**Comment by jabask3dd3r** [comment]
fix plz

**Comment by ghost** [comment]
https://www.mediafire.com/file/0tarbu5vqrppt24/MCPMappingViewer-1.0.3.jar/file

Try downloading this file. I don’t know why, but 1.12.2 works for me
