### ISSUE TITLE
crash when searching for func_75250_a

### ISSUE THREAD

**Issue by bspkrs** [bspkrs/MCPMappingViewer#8]
MCP 9.08, Viewer 0.7.3
to reproduce put "func_75250_a" as search term and click go
     
     
    An error has occurred - give bspkrs this stack trace (which has been copied to the clipboard)
     
    java.lang.NullPointerException
        at bspkrs.mmv.McpMappingLoader$ParamModel.<init>(Unknown Source)
        at bspkrs.mmv.McpMappingLoader.getParamModel(Unknown Source)
        at bspkrs.mmv.gui.MappingGui$MethodTableSelectionListener.valueChanged(Unknown Source)
        at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
        ... 7 more

**Comment by bspkrs** [comment]
Fixed in 1.0.0
